version: "3"

services: 
  db: 
    image: postgres:12-alpine
    volumes: 
      - dev-dc-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env
  api:
    build: .
    command: >
        bash -c "rm -f /api/tmp/pids/server.pid
        && bundle exec rails s -p 3000 -b '0.0.0.0'"  
    volumes: 
      - .:/api
    ports: 
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      RAILS_ENV: development
volumes:
  dev-dc-db:
